version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .
  post_build:
    commands:
      - echo "Zipping application for deployment..."
      - zip -r application.zip * .[^.]* 
artifacts:
  files:
    - application.zip
